# Generated by Django 4.1.1 on 2022-10-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building_c',
            fields=[
                ('name_building', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='images/buildings')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_c',
            fields=[
                ('customer_name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('phone', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Room_c',
            fields=[
                ('id_room', models.AutoField(primary_key=True, serialize=False)),
                ('name_room', models.CharField(max_length=15)),
                ('kind', models.CharField(max_length=35)),
                ('size', models.IntegerField(max_length=3)),
                ('price', models.IntegerField(max_length=5)),
                ('photo', models.ImageField(upload_to='images/rooms')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.building_c')),
            ],
        ),
        migrations.CreateModel(
            name='Rent_c',
            fields=[
                ('number_rent', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.customer_c')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.room_c')),
            ],
        ),
    ]
